config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => "users/registrations"
  }
  
  root 'home#top'
  get 'home/about'
  get '/search' => 'search#search'
  get 'chats/show'
  
  resources :users,only: [:show,:index,:edit,:update] do
    member do
      get :following, :followers
    end
  end

  resources :books do
    resource :favorites,only: [:create, :destroy]
    resources :book_comments,only: [:create, :destroy]
  end

  resources :relationships, only: [:create, :destroy]

  resources :chats, only: [:create]
  resources :rooms, only: [:create,:show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/chat.rb
class Chat < ApplicationRecord
  validates :content, presence: true
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :chats, dependent: :destroy
  has_many :user_rooms, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  attachment :profile_image, destroy: false

  #relationshipアソシエーション
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  #チャット機能アソシエーション
  has_many :user_rooms, dependent: :destroy
  has_many :chats, dependent: :destroy

  include JpPrefecture
  jp_prefecture :prefecture_code

  geocoded_by :address_city
  after_validation :geocode, if: :address_city_changed?

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end


  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum: 50}
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :room_id, uniqueness: { scope: :user_id }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    @newbook = Book.new
    @book_comment = BookComment.new
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

  before_action :authenticate_user!, only: [:create]

  def show
  end

  def create
    if UserRoom.where(user_id: current_user.id, room_id: params[:chat][:room_id]).present?
      @chat = Chat.create(params.require(:chat).permit(:user_id, :content, :room_id).merge(user_id: current_user.id))
    else
      flash[:alert] = "メッセージ送信に失敗しました。"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def top
  end

  def about
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :authenticate_user!

  def create
    @room = Room.create
    @entry1 = UserRoom.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = UserRoom.create(params.require(:user_room).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if UserRoom.where(user_id: current_user.id,room_id: @room.id).present?
      @chats = @room.chats
      @chat = Chat.new
      @entries = @room.user_rooms
    else
      redirect_back(fallback_location: root_path)
    end
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def create
    @user = User.new(user_params)

    if @user.save
      sign_in @user
      NotificationMailer.send_confirm_to_user(@user).deliver_now
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :introduction, :profile_image, :postcode, :prefecture_name, :address_city, :address_street, :password,)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new

    @currentUserRoom=UserRoom.where(user_id: current_user.id)
    @userRoom=UserRoom.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserRoom.each do |cu|
        @userRoom.each do |u|
          if cu.room_id == u.room_id
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = UserRoom.new
      end
    end

  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def following
    @user  = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image, :postcode, :prefecture_name, :address_city, :address_street)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>

	<tr>
		<th>follows</th>
		<th>
			<a href="<%= following_user_path(user) %>"><%= user.followings.count %></a>
		</th>
	</tr>

	<tr>
		<th>followers</th>
		<th>
		<a href="<%= followers_user_path(user) %>"><%= user.followers.count %></a>
		</th>
	</tr>
</table>

<% if user == current_user %>
	<div class="row">
		<%= link_to '', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
	</div>
<% else %>
	<%= render 'relationships/follow_button', user: user %>
<% end %>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

	<!-- エラーメッセージ表示-->
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3><
			<ul>
				<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<!-- エラーメッセージ表示-->

	<div class="field">
		<%= f.label :title %>
		<%= f.text_field :name, class: "name" %>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.attachment_field :profile_image, class: "user_image" %>
	</div>

	<div class="field">
		<%= f.label :introduction %>
		<%= f.text_area :introduction, class: "introduction" %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/users/index.html.erb
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

	<div class="col-xs-9">
		<h2>Users</h2>
		<!--users一覧 -->
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
					<td><%= user.name %></td>
					<td>フォロー数 : <%= user.followings.count %></td>
					<td>フォロワー数 : <%= user.followers.count %></td>
					<td><%= render 'relationships/follow_button', user: user %></td>
					<td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--users一覧 -->
	</div>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<!-- チャット機能 -->
		<% unless @user.id == current_user.id %>
			<% if @isRoom == true %>
				<p class="user-show-room"><a href="/rooms/<%= @roomId %>" class="btn btn-block">チャットを始める</a>
			<% else %>
				<%= form_for @room do |f| %>
					<%= fields_for @entry do |e| %>
						<%= e.hidden_field :user_id, value: @user.id %>
					<% end %>
					<%= f.submit "チャットを始める", class:"btn btn-block user-show-chat"%>
				<% end %>
			<% end %>
		<% end %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to user_path(book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<td>
						<% if book.favorited_by?(current_user) %>
							<li>
								<%= link_to book_favorites_path(book), method: :delete do %>
									<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
									<%= book.favorites.count %> いいね
								<% end %>
							</li>
							<% else %>
							<li>
								<%= link_to book_favorites_path(book), method: :post do %>
									<i class="far fa-heart" aria-hidden="true"></i>
									<%= book.favorites.count %> いいね
								<% end %>
							</li>
						<% end %>
					</td>
					<td><%= "コメント数:#{book.book_comments.count}" %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--books一覧 -->
	</div>
</div>

<% if @user == current_user %>
	<h2>Your Map</h2>
	<div id="map"></div>

	<script>
		function initMap() {
			var test ={lat: <%= @user.latitude %>, lng: <%= @user.longitude %>};
			var map = new google.maps.Map(document.getElementById('map'), {
								zoom: 15, 
								center: test
								});
			var transitLayer = new google.maps.TransitLayer();
			transitLayer.setMap(map);

			var contentString = '住所：<%= @user.address_city %>';
			var infowindow = new google.maps.InfoWindow({
				content: contentString
			});

			var marker = new google.maps.Marker({
										position:test,
										map: map,
										title: contentString
									});

			marker.addListener('click', function() {
				infowindow.open(map, marker);
			});
		}
	</script>
<% end %>

app/views/users/show_follow.html.erb
<h2>Follow Users</h2>  
  <% if @users.count == 0 %>
    <p>ユーザーはいません</p>
  <% else %>
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @user.followings.each do |user| %>
        <tr>
          <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
          <td><%= user.name %></td>
          <td>フォロー数 : <%= user.followings.count %></td>
          <td>フォロワー数 : <%= user.followers.count %></td>
          <td><%= render 'relationships/follow_button', user: user %></td>
          <td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>

app/views/users/show_follower.html.erb
<h2>Follower Users</h2>
  <% if @users.count == 0 %>
    <p>ユーザーはいません</p>
  <% else %>
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @user.followers.each do |user| %>
        <tr>
          <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
          <td><%= user.name %></td>
          <td>フォロー数 : <%= user.followings.count %></td>
          <td>フォロワー数 : <%= user.followers.count %></td>
          <td><%= render 'relationships/follow_button', user: user %></td>
          <td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>